name: rxdb-supabase

on: [push]

jobs:
  rxdb-supabase:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - run: npm ci

      - name: Dependencies audit
        run: npm audit --audit-level=moderate --omit=dev

      - name: Build
        run: npm run build

      - name: Format check
        run: npm run format:check

      - name: Lint check
        run: npm run lint:check
        continue-on-error: true

      - name: Spell check
        run: npm run spell:check
        continue-on-error: true

      - name: Tests
        run: npm run test

      - name: Integration Tests
        run: npm run integration-test
        env:
          TEST_SUPABASE_URL: ${{ secrets.TEST_SUPABASE_URL }}
          TEST_SUPABASE_API_KEY: ${{ secrets.TEST_SUPABASE_API_KEY }}
